# Generated by Django 4.2.5 on 2023-09-30 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_rename_event_space_reservation_event_space_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='event_space_1',
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='event_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.style'),
        ),
    ]
