# Generated by Django 4.2.5 on 2023-09-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0009_remove_reservation_event_space_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
